### PR TITLE
Fix/yesno field checked state

### PR DESCRIPTION
**Pull request by bertrandmc**
# Description

Bug: YesNo field not checked when going back a form journey via back button. 

Steps to reproduce:
1. Open any form with a YesNo question
2. Select Yes and click next
3. Click `Back` button
4. The YesNo question has a blank state instead of previous selected "Yes"

Problem:
Values submitted by form are string "true" or "false" and YesNo getViewModel was strictly comparing booleans
```javascript
 viewModel.items = this.items.map(({ text, value }) => ({
    text,
    value,
    checked: value === formData[this.name],
 }));
```

- Change: Refactor so checked state is correctly evaluated with either string or boolean values.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [X] I have added tests that prove my fix is effective
- [X] I have manually tested to confirm bug is fixed

# Checklist:

- [X] My changes do not introduce any new linting errors
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation and versioning
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I have rebased onto main and there are no code conflicts
- [X] I have checked deployments are working in all environments
- [X] I have updated the architecture diagrams as per Contribute.md

### CODE REVIEW

**Review by jenbutongit — APPROVED** [review]

**Comment by TheSpartan1980** [comment]
@bertrandmc I'll put this through its paces now

**Comment by TheSpartan1980** [comment]
Screenshot 2021-06-18 at 13 36 02
Screenshot 2021-06-18 at 13 32 26
Screenshot 2021-06-18 at 13 32 11
Screenshot 2021-06-18 at 13 38 30

**Review by TheSpartan1980 — APPROVED** [review]
Tested locally, no issues relating to this change.

**Comment by jenbutongit** [comment]
@TheSpartan1980 strikes again 💪

**Pull request merged**
