### PR TITLE
tests(designer): update unit tests for some components

### PR DESCRIPTION
**Pull request by RichardBray**
# Description

- add unit tests to untested designer components
- replace the **hapi** test imports with react testing library for two components
- for componentListSelect and componentCreateList

_For a more detailed description of what this PR is doing please look at the commit messages._

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] This change requires a documentation update

# How Has This Been Tested?

- [x] Unit Tests

# Checklist:

- [x] My changes do not introduce any new linting errors
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation and versioning
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] I have rebased onto master and there are no code conflicts
- [ ] I have checked deployments are working in all environments
- [ ] I have updated the architecture diagrams as per Contribute.md

### CODE REVIEW

**Comment by jenbutongit** [comment]
@RichardBray I think the tests are failing because your file name is `xxx.test.tsx`. Jest is configured to be matching `*.jest` files, so jest.describe is not available

**Comment by RichardBray** [comment]
> @RichardBray I think the tests are failing because your file name is `xxx.test.tsx`. Jest is configured to be matching `*.jest` files, so jest.describe is only available for .jest. files

Really!? There were already .test files in the project, I guess maybe in the part of the project I'm working on the settings might be different? Okay I'll mess around with the file names tomorrow and see if it fixes anything.

**Comment by jenbutongit** [comment]
yep. hapi/lab is looking for .test. and is setting up the DOM that way. They will be importing { describe } from hapi/code iirc

**Comment by RichardBray** [comment]
> yep. hapi/lab is looking for .test. and is setting up the DOM that way. They will be importing { describe } from hapi/code iirc

Cool, I'll try that. Actually, I've seen how Betrand has written tests without sinon in his PR (https://github.com/XGovFormBuilder/digital-form-builder/pull/270)  so I'll make this PR a draft again and make those changes before I make it ready for review again.

**Review by jenbutongit — APPROVED** [review]
LGTM!! Thank you! 💪💪

**Comment by bertrandmc** [comment]
@RichardBray just to explain, this is because we are migrating from Hapi/lab to Jest, ATM hapi test files are named `*.test.ts{x}` and jest `*.jest.ts{x}`.

**Pull request merged**
