### PR TITLE
#808 Fixing Edit page hints

### PR DESCRIPTION
**Pull request by adamdavies1**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Please also include any acceptance criteria if you have any.

- Changing the edit help texts to match the add page help text.
- [Link to issue](https://github.com/XGovFormBuilder/digital-form-builder/issues/808)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce
the testing if necessary.

Before PR's can be merged they will need to be tested by QA and approved where
applicable. To flag the change to QA assign **@XGovFormBuilder/qa** as one of the reviewers.

- [ ] Click edit page, the help text on the "edit page" page should match the ones on the "add page" page. Compare them to see

# Checklist:

- [x] My changes do not introduce any new linting errors
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have rebased onto main and there are no code conflicts
- [x] I have checked deployments are working in all environments

### CODE REVIEW

**Review by RichardBray — COMMENTED** [review]
Is there a content writer that needs to double check the text before it goes live? Code wise this looks fine.

**Comment by adamdavies1** [comment]
> Is there a content writer that needs to double check the text before it goes live? Code wise this looks fine.

Unsure on this myself @jenbutongit?

**Comment by RichardBray** [comment]
> > Is there a content writer that needs to double check the text before it goes live? Code wise this looks fine.
> 
> Unsure on this myself @jenbutongit?

I had a chat with Jen (via Slack) and we don't have a content writer :(
So I will re-review with that in mind.

**Comment by adamdavies1** [comment]
> This looks fine although since some of the text is used verbatim in other places, would it make sense to try and unify them somehow instead of having the same piece of text in two places?
> 
> Like having a new section that utilises the copy or using `sectionOption.helpText` instead of `page.sectionOption ` if that makes sense.
> 
> Happy to elaborate if it doesn't.

@RichardBray So the reason why i kept them separate because through the life time of the app the wording has been changing for different sections. Iv kept it like this to avoid us having to do a rework later. What do you think?

**Comment by jenbutongit** [comment]
Text changes are mainly harmless, we can always revert them. Let's keep an eye on it? They've been suggested by @delaynesr so happy enough for it to go in. thanks all!

**Review by jenbutongit — APPROVED** [review]

**Pull request merged**
