### PR TITLE
Fix: Outputs not displaying

### PR DESCRIPTION
**Pull request by adamdavies1**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Please also include any acceptance criteria if you have any.

- Outputs should now display on the outputs page
- [Link to the issues for bug recreation steps](https://github.com/XGovFormBuilder/digital-form-builder/issues/812)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce
the testing if necessary.

Before PR's can be merged they will need to be tested by QA and approved where
applicable. To flag the change to QA assign **@XGovFormBuilder/qa** as one of the reviewers.

- [ ] Create any output and check if it displays

# Checklist:

- [ ] My changes do not introduce any new linting errors
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have rebased onto main and there are no code conflicts
- [ ] I have checked deployments are working in all environments

### CODE REVIEW

**Review by RichardBray — COMMENTED** [review]
I appreciate this is one of those pull-requests where the lines of code are probably less than the lines of sentences that would be needed to explain what the change is doing. 

But as someone who isn't as familiar as others with this project, a few descriptive words to explain what this is fixing would be super helpful 😁

**Comment by adamdavies1** [comment]
> I appreciate this is one of those pull-requests where the lines of code are probably less than the lines of sentences that would be needed to explain what the change is doing.
> 
> But as someone who isn't as familiar as others with this project, a few descriptive words to explain what this is fixing would be super helpful 😁

@RichardBray there should now be a link to the related issue in the description

**Review by RichardBray — APPROVED** [review]
I've noticed you've upgraded the way context is working in this component but was that the only thing that caused the issue 🤔 

I assumed React was backwards compatible and supports the legacy way of doing things. Maybe I was wrong?

**Comment by SentientHousePlant** [comment]
Thanks for closing my issue peeps! 💖

**Pull request merged**
