### PR TITLE
Forms 254 adjust pre defined form

### PR DESCRIPTION
**Pull request by bertrandmc**
# Description

Ticket: FORMS-215

- Adjust designer's new form JSON.
- Extend eslint with plugin:json/recommended (lint was failing to validate `new-form.json` changes. 

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [X] I have added unit tests to verify my changes. 
- [X] New and existing unit tests pass locally with my changes
- [X] I have manually tested the application to confirm initial empty form is correct

# Checklist:

- [X] My changes do not introduce any new linting errors
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation and versioning
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I have rebased onto master and there are no code conflicts
- [X] I have checked deployments are working in all environments
- [X] I have updated the architecture diagrams as per Contribute.md

### CODE REVIEW

**Comment by bertrandmc** [comment]
@TheSpartan1980 I have fixed one of the smoke tests but looking at the toher I think you might want to review it because adjusting it might require some design changes. With the new-fom configuration we now have 3 pages that are linked by default, `First page` -> `Second page` -> `Summary`.

**Comment by bertrandmc** [comment]
@TheSpartan1980 I decided to fix the tests in case that facilitates to you, I am making the assumption that it wouldn't be an issue to refactor the test so it adds a new `Third page` linked to the `First page` instead of `Second page`, also because a page can link to multiple pages then the tests is still validating that the page linkage works correctly, please feel free to push changes to this branch as you see fit.

**Comment by TheSpartan1980** [comment]
@bertrandmc Good from a QA perspective

**Review by kakanisridhar — COMMENTED** [review]
LGTM

**Review by kakanisridhar — APPROVED** [review]

**Pull request merged**
