### PR TITLE
Removed @wip tags

### PR DESCRIPTION
**Pull request by TheSpartan1980**
# Description

Initial analysis into what is causing random failures in the smoke-tests

### CODE REVIEW

**Comment by RichardBray** [comment]
@TheSpartan1980 Do you know why the @wip tags were added in the first place?

**Comment by TheSpartan1980** [comment]
> @TheSpartan1980 Do you know why the @wip tags were added in the first place?

Hi @RichardBray yes I do something has changed recently that cause random test failures, if a @wip tag is added to a scenario Cucumber will ignore the test as it's specified in the wdio.conf.js file.

**Comment by RichardBray** [comment]
> > @TheSpartan1980 Do you know why the @wip tags were added in the first place?
> 
> Hi @RichardBray yes I do something has changed recently that cause random test failures, if a @wip tag is added to a scenario Cucumber will ignore the test as it's specified in the wdio.conf.js file.

Ah cool didn't know that, thanks for the explanation 👍

**Comment by TheSpartan1980** [comment]
Ported changes to another PR.

**Pull request closed without merging**
