### PR TITLE
Feature/runner-health-check-route

### PR DESCRIPTION
**Pull request by bertrandmc**
# Description

- Implement Runner's `/health-check` route.

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [X] I have added unit tests that confirm feature is effective
- [X] New and existing unit tests pass locally with my changes

# Checklist:

- [X] My changes do not introduce any new linting errors
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation and versioning
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I have rebased onto master and there are no code conflicts
- [X] I have checked deployments are working in all environments
- [X] I have updated the architecture diagrams as per Contribute.md

### CODE REVIEW

**Review by jenbutongit — CHANGES_REQUESTED** [review]
LGTM, but can we wrap the route only for non-prod deployments? it might affect FCDO etc since they've already got it in prod

**Comment by bertrandmc** [comment]
We want this in prod at HO. Let me check ask FCDO team.

**Comment by jenbutongit** [comment]
np. maybe it would be a different flag then, "HEALTH_CHECK_ROUTE=true"?

**Comment by bertrandmc** [comment]
@jenbutongit Trevor confirmed it is fine.
> "... go ahead.. We were using /status but that's not really designed to be a healthcheck at all"

**Review by jenbutongit — APPROVED** [review]

**Review by jenbutongit — DISMISSED** [review]

**Review by jenbutongit — APPROVED** [review]
😎

**Review by jenbutongit — APPROVED** [review]

**Pull request merged**
