### PR TITLE
bug/designer-failing-put-post-STP-750-STP-751

### PR DESCRIPTION
**Pull request by jenbutongit**
# Description

For some reason doing schema.validate was throwing an error. the error signature matched this issue: https://github.com/sideway/joi/issues/2203. ¯\_(ツ)_/¯. This is just a patch. I'll open another ticket to sync up and update the joi dependencies. I believe @andymoody tried to update them in engine/runner on a hack day but ran into some issues. 

- After importing the schema, I'm compiling the schema using the `legacy` flag
- I am doing compiledSchema.validate instead of joi.validate(..) 
- ~Blank new-form. Because no path values were filled in we were getting a validation error there too.~ Gave the first page a path so we don't get a validation error

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

- [x] click testing, monitoring network inspector 

# Checklist:

- [x] My changes do not introduce any new linting errors 
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation and versioning
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have rebased onto master and there are no code conflicts

### CODE REVIEW

**Comment by nattrass** [comment]
@jenbutongit , are you able to explain what is going on with the blank new form in a bit more detail? Does that mean I won't have a pre-defined empty page and summary on a new form?

**Comment by jenbutongit** [comment]
yes. I can add them back in with default values if you prefer?

**Comment by nattrass** [comment]
> yes. I can add them back in with default values if you prefer?

yes, definitely, let's keep the existing behaviour the same.

**Review by nattrass — APPROVED** [review]
Tested and is now behaving as expected.

**Comment by jenbutongit** [comment]
closing in favour of #147

**Pull request closed without merging**
